global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'botview'
    static_configs:
      - targets: ['botview:3000']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100'] 